added openssl and curl for recent libdovi updates. also added check for cargo-c so we don't have to recompile it every time. CLEAN_BUILD is recommended.

diff --git a/scripts/libdovi-build b/scripts/libdovi-build
--- a/scripts/libdovi-build
+++ b/scripts/libdovi-build
@@ -7,5 +7,10 @@ cd "$BUILD/repos/dovi_tool/dolby_vision"
 cargo clean
 
 export RUSTFLAGS="-C target-feature=+crt-static -C link-self-contained=yes"
-cargo install cargo-c --target x86_64-unknown-linux-gnu
+
+if ! cargo install --list | grep -q "cargo-c"; then
+    echo "cargo-c not found, installing..."
+    cargo install cargo-c --target x86_64-unknown-linux-gnu
+fi
+
 cargo cinstall --release --prefix $BUILD/build_libs --library-type staticlib
